// INPUT:  serde, serde_json::Value
// OUTPUT: pub struct TaskStartData, pub struct TaskCompleteData, pub enum TaskFinishReason, pub struct SystemMessageData, pub enum SystemMessageLevel, pub struct FinishData, pub struct ErrorData
// POS:    Defines ACP task lifecycle message types including start, complete, system messages, finish, and error data.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskStartData {
    pub task_id: String,
    /// Human-readable task description (generated by Agent)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskCompleteData {
    pub task_id: String,
    pub finish_reason: TaskFinishReason,
    /// Agent-generated task summary (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskFinishReason {
    Complete,
    Cancelled,
    Error,
    MaxIterations,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemMessageData {
    pub level: SystemMessageLevel,
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SystemMessageLevel {
    Info,
    Warning,
    Error,
    Debug,
}

/// Final completion data (typically follows TaskComplete)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinishData {
    pub output: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorData {
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recoverable: Option<bool>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_task_complete_data_serde() {
        let data = TaskCompleteData {
            task_id: "t-001".to_string(),
            finish_reason: TaskFinishReason::Complete,
            summary: Some("Done".to_string()),
        };
        let json = serde_json::to_string(&data).unwrap();
        let deserialized: TaskCompleteData = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.task_id, "t-001");
        assert_eq!(deserialized.finish_reason, TaskFinishReason::Complete);
    }

    #[test]
    fn test_finish_reason_variants() {
        for (json_str, expected) in [
            (r#""complete""#, TaskFinishReason::Complete),
            (r#""cancelled""#, TaskFinishReason::Cancelled),
            (r#""error""#, TaskFinishReason::Error),
            (r#""max_iterations""#, TaskFinishReason::MaxIterations),
        ] {
            let reason: TaskFinishReason = serde_json::from_str(json_str).unwrap();
            assert_eq!(reason, expected);
        }
    }

    #[test]
    fn test_system_message_level_variants() {
        for (json_str, expected) in [
            (r#""info""#, SystemMessageLevel::Info),
            (r#""warning""#, SystemMessageLevel::Warning),
            (r#""error""#, SystemMessageLevel::Error),
            (r#""debug""#, SystemMessageLevel::Debug),
        ] {
            let level: SystemMessageLevel = serde_json::from_str(json_str).unwrap();
            assert_eq!(level, expected);
        }
    }
}
